---
apiVersion: v1
data:
  password: {{ .Values.gitlab.auth.gitlab_password | b64enc }}
kind: Secret
metadata:
  name: {{ include "common.names.shortname" $ }}-gitlab-initial-root-password
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque

{{- if .Values.gitlab.postgresql.install }}
---
apiVersion: v1
data:
  postgresql-password: {{ .Values.gitlab.auth.postgresql_password | b64enc }}
  postgresql-postgres-password: {{ .Values.gitlab.auth.postgresql_postgres_password | b64enc }}
kind: Secret
metadata:
  name: {{ include "common.names.shortname" $ }}-postgresql-password
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
{{- end }}
