{{- if (index .Values "example-app" "otel" "enabled") }}
apiVersion: v1
stringData:
  password: "{{ index .Values "example-app" "otel" "password" }}"
kind: Secret
metadata:
  creationTimestamp: null
  name: example-app-otel-secret
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
{{- end }}
