apiVersion: v2
name: vaix
description: "Combined Helm chart for deploying Istiod and Jaeger together"
type: application
version: 1.0.0
appVersion: "1.0"
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
sources:
  - https://github.com/SourceMation/charts.git
keywords:
  - istio
  - jaeger
  - tracing
dependencies:
  - name: base
    version: 1.24.1
    repository: https://istio-release.storage.googleapis.com/charts
    alias: base
  - name: istiod
    version: 1.24.1
    repository: https://istio-release.storage.googleapis.com/charts
    alias: istiod
  - name: jaeger
    version: 3.3.2
    repository: https://jaegertracing.github.io/helm-charts
    alias: jaeger
kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
  - name: Jarosław Mazurkiewicz
    email: jaroslaw.mazurkiewicz@linuxpolska.pl
annotations:
  catalog.cattle.io/display-name: vaix
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/release-name: vaix
  catalog.cattle.io/display-name: vaix
