apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgloader.fullname" . }}
  labels:
    {{- include "pgloader.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pgloader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pgloader.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: dimitri/pgloader:{{ .Values.image.tag | default .Chart.AppVersion }}
          command: ["pgloader","mysql://$(MYDB_USER):$(MYDB_PASSWORD)@$(MYDB_HOSTNAME)/","postgresql://$(PGDB_USER):$(PGDB_PASSWORD)@$(PGDB_HOSTNAME)/postgres"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYDB_HOSTNAME
              value: {{ .Values.env.MYDB_HOSTNAME | quote}}
            - name: PGDB_HOSTNAME
              value: {{ .Values.env.PGDB_HOSTNAME | quote}}
            - name: MYDB_USER
              value: {{ .Values.env.MYDB_USER | quote}}
            - name: PGDB_USER
              value: {{ .Values.env.PGDB_USER | quote}}
            - name: MYDB_PASSWORD
              value: {{ .Values.env.MYDB_PASSWORD | quote }}
            - name: PGDB_PASSWORD
              value: {{ .Values.env.PGDB_PASSWORD | quote}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
