{{- /*
*/}}
{{- if and ( eq $.Values.scope "cluster") ( $.Values.selfSigned.enabled ) }}
  {{- with $.Values.selfSigned }}
---
apiVersion: cert-manager.io/v1
  {{- if eq $.Values.scope "cluster" }}
kind: ClusterIssuer
metadata:
  name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-init
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
kind: Issuer
metadata:
  name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-init
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  namespace: {{ include "common.names.namespace" $ }}
  {{- end }} 
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-ca
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  isCA: true
  commonName: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}
  secretName: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-init
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
  {{- if eq $.Values.scope "cluster" }}
kind: ClusterIssuer
metadata:
  name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-issuer
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
kind: Issuer
metadata:
  name: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-issuer
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  namespace: {{ include "common.names.namespace" $ }}
  {{- end }} 
spec:
  ca:
    secretName: {{ default ( include "common.names.shortname" $ ) ( .issuerName ) }}-selfsigned-ca
  {{- end }}
{{- end }}
