apiVersion: v2
name: cicd-classic-stack-app
description: A Helm chart for Kubernetes
type: application
version: 1.0.2

appVersion: "1.0.0"

annotations:
  catalog.cattle.io/display-name: "CI/CD Classic Stack"
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: cicd-classic

home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png

keywords:
- cicd-classic-stack-app
- cicd

kubeVersion: '>=1.19.0-0'

maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
sources:
- https://github.com/linuxpolska/ezd-rp.git


dependencies:
- name: common
  repository: https://sourcemation.github.io/charts/
  version: 0.1.x

- condition: global.sonarqubeApp.enabled
  name: sonarqube
  repository: https://SonarSource.github.io/helm-chart-sonarqube
  version: 10.6.1+3163

- condition: global.harborApp.enabled
  name: harbor
  repository: https://helm.goharbor.io
  version: 1.14.2

- condition: global.forgejoApp.enabled
  name: forgejo
  repository: oci://codeberg.org/forgejo-contrib
  version: 7.0.3

- condition: global.coderApp.enabled
  name: coder
  repository: https://helm.coder.com/v2
  version: 2.13.2

- condition: global.coderApp.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.19

- condition: global.jenkinsApp.enabled
  name: jenkins
  repository: https://charts.jenkins.io
  version: 5.5.1

