
global:
  sonraqubeApp:
    enabled: true
  harborApp:
    enabled: true
  forgejoApp:
    enabled: true
  coderApp:
    enabled: true

sonarqube:
  persistence:
    enabled: true
  seccompProfile: {}
  prometheusMonitoring:
    podMonitor:
      enabled: true
  
harbor:
  expose:
    type: ingress
    ingress:
      hosts:
        core: harbor.apps.example.com
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

forgejo:
  gitea:
    additionalConfigSources:
      - secret:
        secretName: forgejo-configuration
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  ingress:
    enabled: true
    hosts:
    - host: forgejo.apps.example.com
      paths:
        - path: /
          pathType: Prefix
  
  postgresql-ha:
    enabled: true
    global:
      postgresql:
        auth:
          password: gitea
          database: gitea
          username: gitea
        service:
          ports:
            postgresql: 5432

coder:
  coder:
    env:
      - name: coder-db-postgresql
        valueFrom:
          secretKeyRef:
            name: coder-db-url
            key: url
    ingress:
      enable: true
      host: "coder.apps.example.com"

postgresql:
  auth:
    username: coder
    password: CODER_password
    database: coderi
  persistence:
    size: 10Gi
  nameOverride: "coder"
  fullnameOverride: ""
