{{- if and .Values.global.basicAuth.username .Values.global.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-auth
  namespace: {{ include "monitoring.smNamespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.basicAuth.username | b64enc }}
  password: {{ .Values.global.basicAuth.password | b64enc }}
{{- end }}  