---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: elastic-opentelemetry
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
#            cors:
#              allowed_origins:
#              - http://*
#              - https://*

      zipkin:
        endpoint: 0.0.0.0:9411
        parse_string_tags: false
        include_metadata: true
        cors:
          allowed_origins:
          - http://*
          - https://*

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
#        send_batch_size: 10000
#        timeout: 10s
    exporters:
      debug:
        verbosity: detailed 
      otlp/elastic: 
        endpoint: "elm-apm-http.elastic-eck.svc.cluster.local:8200"
        compression: none
        tls:
          insecure: true
        headers:
          Authorization: "Bearer 39MK5Gm1UhI1F91G76zG3mGF"
#          X-P-Stream: "demo"
#          X-P-TAG-tag1: "value1"
#          X-P-META-meta1: "value1"
#          Content-type: "application/json"

#      otlphttp/apm: 
#        endpoint: "https://apm-tst.apps.dev0.lab.linuxpolska.pl:443"
#        headers:
#          # Elastic APM Server secret token
#          Authorization: "Bearer E2D3ytLiaI236F62x2n6Rvt4"
#        tls:
#          # insecure doesnt work
#          insecure: true
#        compression: none



    service:
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [memory_limiter, batch]
          exporters: [otlp/apm]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp/apm]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp/apm]
