global:
  elastic:
    enabled: true
  istiod:
    enabled: true
  jaeger:
    enabled: true
  rancher-monitoring:
    enabled: false


jaeger:
  agent:
    service:
      type: ClusterIP
      zipkinThriftPort: 5775
      binaryPort: 6832
      compactPort: 6831
      samplingPort: 5778
  collector:
    service:
      grpc:
        port: 14250
      zipkin:
        port: 9411
  query:
    basePath: /jaeger
    service:
      port: 16686
    ingress:
      enabled: true

istiod:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 99
