
global:
  conjur-oss:
    enabled: true
  sealed-secrets:
    enabled: true
  external-secrets:
    enabled: true
  kyverno:
    enabled: true 
  kubearmor:
    enabled: false
  kubewarden-defaults:
    enabled: false
  neuvector:
    enabled: true

conjur-oss:
  dataKey: "docker run --rm cyberark/conjur data-key generate"
kyverno:
  test:
    securityContext: []
  webhooksCleanup:
    securityContext: []
  policyReportsCleanup:
    securityContext: []
  cleanupJobs:
    admissionReports:
      securityContext: []
    clusterAdmissionReports:
      securityContext: []
  admissionController:	
    initContainer:
      securityContext: []
    container:
      securityContext: []
  backgroundController:
    securityContext: []
  cleanupController:
    securityContext: []
  reportsController:
    securityContext: []
external-secrets:
  securityContext: []
  webhook:
    securityContext: []
  certController:
    securityContext: []
  installCRDs: false
sealed-secrets:
  server:
    ingress:
      enabled: true

