jenkins:
  controller:
    affinity: {}
    nodeSelector: {}
    admin:
      username: "admin"
      password: "P@ssword1"
    disableRememberMe: false
    image:
      #registry: ""
      #repository: ""
      #tag: ""
      #tagLabel: ""
      pullPolicy: "Always"
    imagePullSecretName: ""
    ingress:
      enabled: true
      apiVersion: "networking.k8s.io/v1"
      ingressClassName: ""
      cert:
        issuerName: "default-selfsigned-ca"
        issuerKind: "ClusterIssuer"
      hostName: "jenkins.apps.example.com"
      tls:
        - secretName: "jenkins-tls-cert"
          hosts:
            - "{{ .Values.controller.ingress.hostName }}"
    installPlugins:
      - kubernetes:4306.vc91e951ea_eb_d
      - workflow-aggregator:600.vb_57cdd26fdd7
      - git:5.5.2
      - configuration-as-code:1873.vea_5814ca_9c93
      - cloudbees-disk-usage-simple:232.v713eeed2e1f4
      - prometheus:795.v995762102f28
    additionalPlugins:
      - pipeline-stage-view:2.34
      - pipeline-utility-steps:2.18.0
      - generic-webhook-trigger:2.2.5
      - rebuild:332.va_1ee476d8f6d
    prometheus:
      enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "512m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    serviceType: ClusterIP
    servicePort: 8080
    targetPort: 8080
    javaOpts: >
      -Xmx2g
      -Djenkins.install.runSetupWizard=false
      -Dorg.jenkinsci.plugins.casc.ConfigurationAsCode.systemConfig=/var/jenkins_home/casc_configs/jenkins-casc.yaml
    updateStrategy: {}
  persistence:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: ""
    size: "8Gi"
