{{- $ssl := . }}
{{- include "conjur-oss.ssl-cert-gen" $ssl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-ssl-ca-cert
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ssl-cert
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if not .Values.ssl.caCert }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
type: kubernetes.io/tls
data:
{{- if .Values.ssl.caCert }}
  tls.crt: {{ .Values.ssl.caCert }}
  tls.key: {{ .Values.ssl.caKey }}
{{- else }}
  tls.crt: {{ .caCrt }}
  tls.key: {{ .caKey }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-ssl-cert
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ssl-cert
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if not .Values.ssl.caCert }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
type: kubernetes.io/tls
data:
{{- if .Values.ssl.caCert }}
  tls.crt: {{ .Values.ssl.cert }}
  tls.key: {{ .Values.ssl.key }}
{{- else }}
  tls.crt: {{ .certCrt }}
  tls.key: {{ .certKey }}
{{- end }}
