image:
  tag: "4.4.2"

env:
  PGPOOL_PARAMS_BACKEND_HOSTNAME0: "mypostgres"
  PGPOOL_PARAMS_BACKEND_FLAG0: "ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER"
  PGPOOL_PARAMS_BACKEND_HOSTNAME1: "mypostgres-replica"
  PGPOOL_PARAMS_BACKEND_FLAG1: "DISALLOW_TO_FAILOVER"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "postgres"
