{{- /*
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/README.asciidoc
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/packetbeat_dns_http.yaml
*/}}

{{- /*
{{- if and .Values.elasticsearch.enabled .Values.kibana.enabled }}


---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ include "common.names.shortname" $ }}-mon-packet
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  type: packetbeat
  version: {{ default .Chart.AppVersion }}
  image: docker.elastic.co/beats/packetbeat:{{ default .Chart.AppVersion }}
  elasticsearchRef:
    name: {{ include "common.names.shortname" $ }}
  kibanaRef:
    name: {{ include "common.names.shortname" $ }}
  config:
    packetbeat.interfaces.device: any
    packetbeat.protocols:
    - type: dns
      ports: [53]
      include_authorities: true
      include_additionals: true
    - type: http
      ports: [80, 8000, 8080, 9200]
    packetbeat.flows:
      timeout: 30s
      period: 10s
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        terminationGracePeriodSeconds: 30
        hostNetwork: true
        automountServiceAccountToken: true # some older Beat versions are depending on this settings presence in k8s context
        dnsPolicy: ClusterFirstWithHostNet
        initContainers:
        - name: wait-for
          image: quay.io/eurolinux/eurolinux-9:latest
          command:
          - /bin/sh
          - -c
          - >
            set -x;
            until curl -f -k -L https://{{ include "common.names.shortname" $ -}}-kb-http:5601; do sleep 2; done
#        initContainers:
#        - name: wait-for
#          image: busybox:latest
#          command:
#          - /bin/sh
#          - -c
#          - >
#            set -x;
#            until wget -q --spider --no-check-certificate https://{{ include "common.names.shortname" $ -}}-kb-http:5601; do sleep 2; done

        containers:
        - name: packetbeat
          securityContext:
            runAsUser: 0
            capabilities:
              add:
              - NET_ADMIN

{{- end }}

*/}}
