{{- /*
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  name: cert-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  name: cert-my-selfsigned-ca
#  namespace: cert-manager
spec:
  isCA: true
  commonName: cert-my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cert-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  name: cert-my-ca-issuer
spec:
  ca:
    secretName: cert-root-secret

*/}}
