annotations:
  catalog.cattle.io/display-name:  Monitoring Stack
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: monitoring-stack-app 
  catalog.cattle.io/auto-install: monitoring-stack-crd=match
apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: global.elasticApp.enabled
  name: elastic
  repository: https://sourcemation.github.io/charts
  version: 1.4.0
#- condition: global.jaegerApp.enabled
#  name: jaeger
#  repository: https://jaegertracing.github.io/helm-charts 
#  version: 3.0.6
description: Set of charts for monitoring
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- elastic
- elasticsearch
- kibana
- apm
- monitoring
- fleet  
#- istio
#- jaeger
kubeVersion: '>=1.25.0-0 <1.30.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: monitoring-stack-app
sources:
- https://github.com/SourceMation/charts.git
type: application
version: 1.1.0
