{{- if or .Values.plugins.kyverno .Values.global.plugins.kyverno -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-kyverno-plugin
  namespace: {{ include "monitoring.smNamespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- with .Values.serviceMonitor.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        {{- include "kyvernoplugin.selectorLabels" . | nindent 8 }}
  {{- with .Values.kyverno.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
  - port: rest
    {{- if and .Values.global.basicAuth.username .Values.global.basicAuth.password }}
    basicAuth:
      password:
        name: {{ include "monitoring.fullname" . }}-auth
        key: password
      username:
        name: {{ include "monitoring.fullname" . }}-auth
        key: username
    {{- else if .Values.global.basicAuth.secretRef }}
    basicAuth:
      password:
        name: {{ .Values.global.basicAuth.secretRef }}
        key: password
      username:
        name: {{ .Values.global.basicAuth.secretRef }}
        key: username
    {{- end }}
    honorLabels: {{ .Values.kyverno.serviceMonitor.honorLabels }}
    {{- if .Values.kyverno.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.kyverno.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.kyverno.serviceMonitor.interval }}
    interval: {{ .Values.kyverno.serviceMonitor.interval }}
    {{- end }}
    relabelings:
    - action: labeldrop
      regex: pod|service|container
    - targetLabel: instance
      replacement: policy-reporter
      action: replace
    {{- with .Values.kyverno.serviceMonitor.relabelings }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.kyverno.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
