replicaCount: 1

imagePullSecrets:
  - name: quay-creds

image:
  repository: quay.io/eurolinux/eurolinux-9-postgresql
  tag: "eurolinux-9-postgresql-14.8.0-amd64"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

affinity: {}
nodeSelector: {}

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: 10Gi
  storageClass: default

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

healthcheck:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

postgresql:
  initdbArgs: "--data-checksums"
  maxConnections: "100"
  sharedBuffers: "128MB"
  effectiveCacheSize: "340MB"
  maintenanceWorkMem: "64MB"
  walBuffers: "4MB"
  sslMode: "disable"
