{{- if .Values.eckFleet.enabled }}
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: {{ include "common.names.fullname" . }}-fleet
  namespace: {{ include "common.names.namespace" . }}
spec:
  http:
    service:
      spec:
        type: LoadBalancer
  version: {{ default .Chart.AppVersion }}
  image: docker.elastic.co/beats/elastic-agent:{{ default .Chart.AppVersion }}
  kibanaRef:
    name: {{ include "common.names.fullname" . }}
  elasticsearchRefs:
  - name: {{ include "common.names.fullname" . }}
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-agent-fleet
  deployment:
    replicas: 2
    podTemplate:
      metadata:
        labels:
          scrape: agent
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
#                - key: elastic
#                  operator: In
#                  values:
#                  - all
        containers:
        - name: agent
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 1Gi
{{- if .Values.eckFleet.params.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-fleet-agent-http
  namespace: {{ include "common.names.namespace" . }}
  {{- with .Values.eckFleet.params.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    agent.k8s.elastic.co/name: {{ include "common.names.fullname" . }}-fleet

spec:
  rules:
  - host: {{ .Values.eckFleet.params.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "common.names.fullname" . -}}-fleet-agent-http
            port:
              number: 8220
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.eckFleet.params.ingress.hostname }}
    secretName: {{ include "common.names.fullname" . }}-fleet-agent-http-certs-internal

{{- end }}
{{- end }}

