{{- if .Values.eckApm.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-apm-agent
  namespace: {{ include "common.names.namespace" . }}
  labels:
    agent.k8s.elastic.co/name: {{ $.Release.Name }}-service
    common.k8s.elastic.co/type: agent
spec:
  type: LoadBalancer
  selector:
    agent.k8s.elastic.co/name: {{ $.Release.Name }}-service
  ports:
  - protocol: TCP
    port: 8200
{{- if .Values.eckApm.params.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-apm-agent-http
  namespace: {{ include "common.names.namespace" . }}
  {{- with .Values.eckApm.params.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
    apm.k8s.elastic.co/name: {{ $.Release.Name }}

spec:
  rules:
  - host: {{ .Values.eckApm.params.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}-apm-agent
            port:
              number: 8200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.eckApm.params.ingress.hostname }}
    secretName: {{ $.Release.Name }}-kb-http-certs-internal

{{- end }}

{{- end }}


{{- /*
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-apm-agent-grpc
  namespace: {{ include "common.names.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    apm.k8s.elastic.co/name: {{ $.Release.Name }}
spec:
  rules:
  - host: {{ .Values.eckApm.params.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}-apm-agent
            port:
              number: 8200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.eckApm.params.ingress.hostname }}
    secretName: {{ $.Release.Name }}-kb-http-certs-internal
*/}}

