---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server-{{ include "common.names.namespace" $ }}
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
    - replicasets
  verbs:
    - get
    - watch
    - list
- apiGroups: ["batch"]
  resources:
    - jobs
  verbs:
    - get
    - watch
    - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: {{ include "common.names.namespace" $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server-{{ include "common.names.namespace" $ }}
subjects:
- kind: ServiceAccount
  name: fleet-server
  namespace: {{ include "common.names.namespace" $ }}
roleRef:
  kind: ClusterRole
  name: fleet-server-{{ include "common.names.namespace" $ }}
  apiGroup: rbac.authorization.k8s.io

