name: 🐞 Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Before you open the bug report, please check the README of the appropriate helm chart:
          - [README](https://github.com/SourceMation/charts/blob/main/charts/README.md)

        Please fill in as much information as you can.
  - type: textarea
    attributes:
      label: Short bug description
      description: What happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Chart name and version
      description: Name and version of the affected chart
      placeholder: 'example: sourcemation/elastic-1.4.0'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Architecture used
      description: Select the architecture of the host where the containers are failing
      options:
        - amd64
        - arm64
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: How can we reproduce your error? Does it happen every time?
      placeholder: |
        1. In the following environment...
        2. Using this configuration...
        3. Execute command '...'
        4. Wait for error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Content of the values.yml file or command line parameters
      description: Add any parameters used by the '--set' option or the whole values.yaml used by the '-f' option
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe the expected behavior
  - type: textarea
    attributes:
      label: Actual result
      description: Describe the actual result or include the entire error/exception
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
