replicaCount: 1

imagePullSecrets:
  - name: quay-creds

image:
  repository: quay.io/eurolinux/eurolinux-9-redis
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

affinity: {}
nodeSelector: {}

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: 10Gi
  storageClass: default

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

healthcheck:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

redis:
  datadir: /data
  nodeConfDir: /node-conf
  extConfFile: /etc/redis/external.conf.d/redis-additional.conf
  majorVersion: v7