apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.names.shortname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
{{- with .Values.cnpg }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
  {{- if .Values.global.create.enabled }}
  bootstrap:
    initdb:
      database: {{ include "common.names.shortname" $ }}
      owner: {{ .Values.global.users.pgAppUser }}
      secret:
        name: postgresql-app-{{ include "common.names.shortname" $ }}
      localeCollate: 'pl_PL.utf8'
      localeCType: 'pl_PL.utf8'
      dataChecksums: false
  {{- end }}
  {{- if .Values.global.import.enabled }}
  externalClusters:
  - name: source-cluster
    connectionParameters:
      host: "{{ .Values.global.import.sourceServiceName }}.{{ .Values.global.import.sourceNamespace }}.svc.cluster.local"
      user: {{ .Values.global.import.sourcePgAppUser }}
      dbname: {{ .Values.global.import.sourceName }}
    password:
      name: postgresql-import-{{ .Values.global.import.sourceName }}
      key: password
  bootstrap:
    initdb:
      database: {{ .Values.global.import.sourceName }}
      owner: {{ .Values.global.users.pgAppUser }}
      import:
        type: microservice
        databases:
        - {{ .Values.global.import.sourceName }}
        source:
          externalCluster: source-cluster
  {{- end }}
  {{- if and .Values.global.recovery.enabled .Values.global.backup.enabled }}
  externalClusters:
  - name: {{ .Values.global.recovery.serverName }}
    barmanObjectStore:
      destinationPath: s3://{{ .Values.global.backup.s3bucket }}/{{ include "common.names.namespace" $ }}/postgresql/
      endpointCA:
        name: "postgresql-s3-ca"
        key: "ca-bundle.crt"
      endpointURL: {{ .Values.global.backup.s3url }}
      s3Credentials:
        accessKeyId:
          name: postgresql-s3-{{ include "common.names.shortname" $ }}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: postgresql-s3-{{ include "common.names.shortname" $ }}
          key: AWS_SECRET_ACCESS_KEY
  bootstrap:
    recovery:
      source: {{ .Values.global.recovery.serverName }}
      owner: {{ .Values.global.users.pgAppUser }}
      secret:
        name: postgresql-app-{{ include "common.names.shortname" $ }}
    {{- if .Values.global.recovery.pitr.enabled }}
    recoveryTarget:
        targetTime: {{ .Values.global.recovery.pitr.datetime }}
    {{- end }}
  {{- end }}
  managed:
    roles:
    - name: {{ .Values.global.users.pgAppUser }}
      comment: user
      createdb: false
      createrole: true
      replication: true
      login: true
      superuser: false
      passwordSecret:
        name: postgresql-app-{{ include "common.names.shortname" $ }}
    - name: {{ .Values.global.users.pgAdmUser }}
      comment: admin
      createdb: true
      createrole: true
      replication: true
      login: true
      superuser: true
      passwordSecret:
        name: postgresql-superuser-{{ include "common.names.shortname" $ }}
  {{- if .Values.global.backup.enabled }}
  backup:
    {{- if or .Values.global.create.enabled .Values.global.import.enabled }}
    target: "prefer-standby"
    {{- end }}
    retentionPolicy: "3d"
    barmanObjectStore:
      destinationPath: s3://{{ .Values.global.backup.s3bucket }}/{{ include "common.names.namespace" $ }}/postgresql/
      endpointCA:
        name: "postgresql-s3-ca"
        key: "ca-bundle.crt"
      endpointURL: {{ .Values.global.backup.s3url }}
      {{- if .Values.global.recovery.enabled }}
      serverName: {{ include "common.names.shortname" $ }}-{{ .Values.global.recovery.nameSuffix }}
      {{- end }}
      s3Credentials:
        accessKeyId:
          name: postgresql-s3-{{ include "common.names.shortname" $ }}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: postgresql-s3-{{ include "common.names.shortname" $ }}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 1
      data:
        compression: gzip
        immediateCheckpoint: true
        jobs: 2
  {{- end }}