---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser-{{ include "common.names.shortname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.users.pgAdmUser }}
  password: {{ .Values.global.users.pgAdmPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app-{{ include "common.names.shortname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.users.pgAppUser }}
  password: {{ .Values.global.users.pgAppPass }}
{{- if .Values.global.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-s3-{{ include "common.names.shortname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.backup.s3secret }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.backup.s3access }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-s3-ca
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
data:
  ca-bundle.crt: {{ .Values.global.backup.s3ca }}
{{- end }}
{{- if eq .Values.global.deploymentMode "import" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-import-{{ .Values.global.import.sourceName }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.import.sourcePgAppUser }}
  password: {{ .Values.global.import.sourcePgAppPass }}
{{- end }}