---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser-{{ .Values.cnpg.cluster.metadata.name }}
  namespace:  {{ .Values.cnpg.cluster.metadata.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.users.pgAdmUser }}
  password: {{ .Values.global.users.pgAdmPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app-{{ .Values.cnpg.cluster.metadata.name }}
  namespace: {{ .Values.cnpg.cluster.metadata.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.users.pgAppUser }}
  password: {{ .Values.global.users.pgAppPass }}
{{- if .Values.global.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-s3-{{ .Values.cnpg.cluster.metadata.name }}
  namespace: {{ .Values.cnpg.cluster.metadata.namespace }}
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.backup.s3secret }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.backup.s3access }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-s3-ca
  namespace: {{ .Values.cnpg.cluster.metadata.namespace }}
data:
  ca-bundle.crt: {{ .Values.global.backup.s3ca }}
{{- end }}
{{- if .Values.global.import.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-import-{{ .Values.global.import.sourceName }}
  namespace: {{ .Values.cnpg.cluster.metadata.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.import.sourcePgAppUser }}
  password: {{ .Values.global.import.sourcePgAppPass }}
{{- end }}