annotations:
  catalog.cattle.io/display-name: Istio (1/1) - Operator
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  #  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
  #  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: istio-operator
  catalog.cattle.io/namespace: istio-system
apiVersion: v2
appVersion: 1.26.2
dependencies:
  - name: common
    repository: https://charts.sourcemation.com/
    version: 0.1.x
  - condition: global.istioOperatorCrd.enabled
    name: base
    version: 1.26.2
    repository: https://istio-release.storage.googleapis.com/charts
  - condition: global.istioOperatorCrd.enabled
    name: istiod
    version: 1.26.2
    repository: https://istio-release.storage.googleapis.com/charts
  - condition: global.istioOperatorCrd.enabled
    name: cni
    version: 1.26.2
    repository: https://istio-release.storage.googleapis.com/charts
  - condition: global.istioOperatorCrd.enabled
    name: ztunnel
    version: 1.26.2
    repository: https://istio-release.storage.googleapis.com/charts
description: Istio is an open source service mesh that layers transparently onto existing distributed applications. Install only once on kubernetes. Security & Monitoring.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
  - security
  - monitoring
  - istio
#kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
  - email: radoslaw.kolba@linuxpolska.com
    name: radkolba-lp
name: istio-operator
sources:
  - https://github.com/SourceMation/charts.git
type: application
version: 0.2.2
