{{- /*

{{- if $.Values.global.istioCrd.enabled }}
  {{- if ne .Release.Namespace "lp-system" }}
---
apiVersion: v1
kind: Namespace
metadata:
  # definicja defaults powoduje problemy z odowalniem sie do zmiennej
  name: {{ default "lp-system"  }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}

  {{- end }}
{{- end }}

*/}}


