annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: only create ServiceMonitor if cluster supports it
    - kind: fixed
      description: rbac templating issues
    - kind: added
      description: define resources for cleanupJobs
    - kind: changed
      description: change to enable webhook cleanup hook by default
    - kind: added
      description: allow pod labels for cleanup jobs
    - kind: added
      description: allow nodeSelector for cleanup jobs
    - kind: added
      description: allow nodeSelector, tolerations and affinity settings for webhooksCleanup
    - kind: added
      description: allow affinity settings for cleanup jobs
    - kind: added
      description: Add helper to handle the labels for cleanup jobs, add component label
  artifacthub.io/links: |
    - name: Documentation
      url: https://kyverno.io/docs
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: v1.10.5
description: Kubernetes Native Policy Management
home: https://kyverno.io/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- validating webhook
- admissions controller
kubeVersion: '>=1.16.0-0'
maintainers:
- name: Nirmata
  url: https://kyverno.io/
name: kyverno
sources:
- https://github.com/kyverno/kyverno
type: application
version: 3.0.7
