apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: 5672
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
  selector:
    app: {{ include "rabbitmq.name" . }}
