apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  serviceName: "{{ include "rabbitmq.fullname" . }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rabbitmq.name" . }}
    spec:
      securityContext:
        fsGroup: 995
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: rabbitmq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "rabbitmq.fullname" . }}-secret
              key: rabbitmq-username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "rabbitmq.fullname" . }}-secret
              key: rabbitmq-password
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        - name: config-volume
          mountPath: /etc/rabbitmq
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "rabbitmq.fullname" . }}
      - name: config-volume
        configMap:
          name: {{ include "rabbitmq.fullname" . }}-config
