apiVersion: v2
name: tekton
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

appVersion: "1.0.0"

annotations:
  catalog.cattle.io/display-name: "Tekton"
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: tekton

home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png

keywords:
- tekton

kubeVersion: '>=1.19.0-0'

maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
sources:
- https://github.com/linuxpolska/ezd-rp.git


dependencies:
- name: common
  repository: https://sourcemation.github.io/charts/
  version: 0.1.x