{{- if $.Values.global.coderApp.enabled }}
---
apiVersion: v1
stringData:
  url: postgres://{{ $.Values.postgresql.auth.username }}:{{ $.Values.postgresql.auth.password }}@{{ include "common.names.shortname" . }}-coder-postgresql/{{ .Values.postgresql.auth.database }}?sslmode=disable
kind: Secret
metadata:
  name: {{ include "common.names.shortname" . }}-coder-db-url

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.shortname" . }}-prometheus 
spec:
  clusterIP: None
  ports:
    - name: prometheus-http
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    app.kubernetes.io/instance: {{ include "common.names.shortname" . }}
    app.kubernetes.io/name: coder
  type: ClusterIP


{{- end }}
