{{- if $.Values.global.forgejoApp.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ .Values.forgejo.gitea.params.additionalConfigSources.secret.secretName }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
type: Opaque
stringData:
  database: |
{{- with index .Values.forgejo "postgresql-ha" "global"}}
    DB_TYPE = postgres
    HOST = {{ $.Release.Name }}-postgresql-ha-postgresql:5432
    NAME = {{ .postgresql.auth.database }}
    PASSWD = {{ .postgresql.auth.password }}
    USER = {{ .postgresql.auth.username }}
{{- end }}
{{- end }}