---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-configuration
type: Opaque
stringData:
  database: |
    DB_TYPE = postgres
    HOST = forgejo-postgresql-ha-postgresql:5432
    NAME = gitea
    PASSWD = gitea
    USER = gitea
