apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-url
spec:
  rules:
  - host: sonar.apps.example.com
    http:
      paths:
      - backend:
          service:
<<<<<<< HEAD
            name: cicd-blad-sonarqube
=======
            name: cicd-blad11-sonarqube
>>>>>>> d2c5f4b (test: chart fixing)
            port:
              number: 9000
        path: /
        pathType: Prefix
