annotations:
  catalog.cattle.io/display-name: Cert-manager - Configuration (2/2)
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: cert-manager-config
  catalog.cattle.io/namespace: cert-manager
apiVersion: v2
appVersion: 1.15.1
dependencies:
- name: common
  repository: https://sourcemation.github.io/charts/
  version: 0.1.x

description: Cert-manager configuration. Install once per k8s. Security.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- security
- cert manager
- cert-manager
kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: cert-manager
sources:
- https://github.com/SourceMation/charts.git
type: application
version: 1.0.0
