global:
  cnpgOperatorCrd:
    enabled: true

cnpg:
  crds:
    create: true
  
  image:
#    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    pullPolicy: IfNotPresent
#  imagePullSecrets: [] 

#  monitoring:
#    podMonitorEnabled: true
#  imagePullSecrets:
#  - name: registry-auth
   
  containerSecurityContext:
    seccompProfile: {}
   
  podSecurityContext:
    seccompProfile: {}

#  updateStrategy: {}
questionsSpec: {}