apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-envs
data:
  PERSISTENCE_ENABLED: {{ .Values.persistence.enabled | quote }}
  DATA_DIR: {{ .Values.redis.datadir | quote }}
  NODE_CONF_DIR: {{ .Values.redis.nodeConfDir | quote }}
  EXTERNAL_CONFIG_FILE: {{ .Values.redis.extConfFile | quote }}
  REDIS_MAJOR_VERSION: {{ .Values.redis.majorVersion | quote }}