apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if and .Values.persistence.storageClass (ne .Values.persistence.storageClass "default") }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
