global:
  adcsIssuerCrd:
    enabled: true
  trustManagerCrd:
    enabled: true

adcs-issuer:
  controllerManager:
    rbac:
      enabled: true
      serviceAccountName: adcs-issuer      
      certManagerNamespace: cert-manager   
      certManagerServiceAccountName: cert-manager 
    replicas: 2
    arguments:
      cluster-resource-namespace: cert-manager
#    environment:
#      KUBERNETES_CLUSTER_DOMAIN: cluster.local
#      ENABLE_WEBHOOKS: "false"                 
#      ENABLE_DEBUG: "true"                    
  
  simulator:
    enabled: false
    exampleCertificate:
      enabled: false

  affinity:
    nodeAffinity: {}                          # Node affinity rules for the simulator pods.
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: kubernetes.io/e2e-az-name
    #         operator: In
    #         values:
    #         - e2e-az1
    #         - e2e-az2
    podAffinity: {}                           # Pod affinity rules for the simulator pods.
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: security
      #       operator: In
      #       values:
      #       - S1
      #   topologyKey: "kubernetes.io/hostname"
    podAntiAffinity: {}                       # Pod anti-affinity rules for the simulator pods.
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   - labelSelector:
      #       matchExpressions:
      #       - key: app
      #         operator: In
      #         values:
      #         - "my-app"
      #     topologyKey: "kubernetes.io/hostname"

trust-manager:
  crds:
    enabled: true
    keep: true
  imagePullSecrets: []
#  - name: "registry-auth"
  image:
    repository: quay.io/jetstack/trust-manager
  defaultPackageImage:
    repository: quay.io/jetstack/cert-manager-package-debian
  affinity: {}
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#            - key: node-role.kubernetes.io/infra
#              operator: In
#              values:
#              - 'true'
  app:
    # The format of trust-manager logging. Accepted values are text or json.
    logFormat: json
    # The verbosity of trust-manager logging. This takes a value from 1-5, with the higher value being more verbose.
    logLevel: 1
    trust:
      namespace: cert-manager
    webhook:
      tls:
        approverPolicy:
          enabled: true
          certManagerNamespace: "cert-manager"
    metrics:
      service:
        servicemonitor:
          enabled: true
