global:
  deploymentMode: 'create'
  users:
    pgAppUser: ''
    pgAppPass: ''
    pgAdmUser: ''
    pgAdmPass: ''
  import:
    sourceName: ''
    sourceNamespace: ''
    sourceServiceName: ''
    sourcePgAppUser: ''
    sourcePgAppPass: ''
  recovery:
    serverName: 'postgresql-production'
    nameSuffix: 'recovery'
    pitr:
      enabled: false
      datetime: ''
  backup:
    enabled: false
    s3url: ''
    s3bucket: ''
    s3access: ''
    s3secret: ''
    s3ca: ''

nameOverride: "cnpg-test"
namespaceOverride: "my-namespace"

# Main
cnpg:
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 2
  replicationSlots:
    highAvailability:
      enabled: true
  monitoring:
    enablePodMonitor: true
  postgresql:
    pg_hba:
    - host all all all password
    parameters:
      max_connections: "100"
      superuser_reserved_connections: "3"
      shared_buffers: "256MB"
      timezone: "Europe/Warsaw"
  resources:
    requests:
      memory: "512Mi"
      cpu: 500m
    limits:
      memory: "512Mi"
      cpu: 500m
  storage:
    storageClass: 'bs-vsphere-c1'
    size: '2Gi'
    resizeInUseVolumes: True
  walStorage:
    size: 1Gi
    resizeInUseVolumes: True
      
customRoles:

  # pooler:
  #   metadata:
  #     name: pgbouncer-test
  #   spec:
  #     instances: 3
  #     type: rw
  #     pgbouncer:
  #       poolMode: session
  #       parameters:
  #         max_client_conn: "1000"
  #         default_pool_size: "10"

# Helm (monitor)
# kube-prometheus-stack:
#   enabled: true
#   kubeControllerManager:
#     enabled: false
#   nodeExporter:
#     enabled: false
#   defaultRules:
#     create: true
#     rules:
#       alertmanager: false
#       etcd: false
#       configReloaders: false
#       general: false
#       k8s: true
#       kubeApiserver: false
#       kubeApiserverAvailability: false
#       kubeApiserverSlos: false
#       kubelet: true
#       kubeProxy: false
#       kubePrometheusGeneral: false
#       kubePrometheusNodeRecording: false
#       kubernetesApps: false
#       kubernetesResources: false
#       kubernetesStorage: false
#       kubernetesSystem: false
#       kubeScheduler: false
#       kubeStateMetrics: false
#       network: false
#       node: true
#       nodeExporterAlerting: false
#       nodeExporterRecording: true
#       prometheus: false
#       prometheusOperator: false
#   prometheus:
#     enabled: true
#     ingress:
#       enabled: true
#       hosts:
#         - prometheus.example.com
#     prometheusSpec:
#       podMonitorSelectorNilUsesHelmValues: false
#       ruleSelectorNilUsesHelmValues: false
#       serviceMonitorSelectorNilUsesHelmValues: false
#       probeSelectorNilUsesHelmValues: false
#       retention: 10d
#       retentionSize: ""
#       replicas: 1
#       logLevel: info
#       affinity: {}
#       resources: {}
#       # requests:
#       #   memory: 400Mi
#       storageSpec: {}
#       ## Using PersistentVolumeClaim
#       ##
#       #  volumeClaimTemplate:
#       #    spec:
#       #      storageClassName: gluster
#       #      accessModes: ["ReadWriteOnce"]
#       #      resources:
#       #        requests:
#       #          storage: 50Gi
#       #    selector: {} 
#   grafana:
#     enabled: true
#     adminPassword: prom-operator
#     defaultDashboardsEnabled: false
#     sidecar:
#         dashboards:
#           enabled: true
#     ingress:
#       enabled: true
#       ingressClassName: nginx
#       hosts:
#         - grafana.example.com
#     # persistence:
#     #   enabled: true
#     #   type: sts
#     #   storageClassName: "storageClassName"
#     #   accessModes:
#     #     - ReadWriteOnce
#     #   size: 20Gi
#     #   finalizers:
#     #     - kubernetes.io/pvc-protection
#   alertmanager:
#     enabled: true




