apiVersion: v1
appVersion: 5.3.0
description: Helm chart for NeuVector's core services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
- email: support@neuvector.com
  name: becitsthere
name: core
version: 2.7.3
