{{- if .Values.controllerManager.rbac.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controllerManager.rbac.serviceAccountName | default (include "chart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}

{{- end }}
