{{- if .Values.simulator.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.simulator.secretName | default "adcs-sim-secret" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.simulator.username | default (randAlphaNum 8) | b64enc }} # Random 8-character username
  password: {{ .Values.simulator.password | default (randAlphaNum 16) | b64enc }} # Random 16-character password

{{- end }}
