{{- if .Values.simulator.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.simulator.issuerName | default "adcs-sim-selfissuer" }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.simulator.secretCertificateName | default "adcs-sim-certificate-secret" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.simulator.secretCertificateName | default "adcs-sim-certificate-secret" }}
  issuerRef:
    name: {{ .Values.simulator.issuerName | default "adcs-sim-selfissuer" }}
    kind: {{ .Values.simulator.issuerKind | default "Issuer" }}
    group: {{ .Values.simulator.issuerGroup | default "cert-manager.io" }}
  dnsNames:
  - {{ .Values.simulator.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
  duration: {{ .Values.simulator.certificateDuration | default "2160h" }} # 90 days by default
  renewBefore: {{ .Values.simulator.certificateRenewBefore | default "360h" }} # 15 days before expiry by default
{{- end }}
