annotations:
  catalog.cattle.io/display-name: Sonarqube (1/1) - App
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/release-name: sonarqube
#  catalog.cattle.io/kube-version: '>=1.29.0-0 < 1.32.0-0'
#  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
apiVersion: v2
appVersion: 2025.4.3
dependencies:
  - name: common
    repository: https://charts.sourcemation.com/
    version: 0.1.x
  - condition: global.sonarqubeApp.enabled
    name: sonarqube
    repository: https://SonarSource.github.io/helm-chart-sonarqube/
    version: 2025.4.3
description: A static code analysis tool that detects bugs, vulnerabilities, and code quality issues. Install many times on kubernetes. Code analysis.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
  - sonarqube
  - static-analysis
  - code analysis
#kubeVersion: '>=1.29.0-0 <1.32.0-0'
maintainers:
  - email: marek.janosz@linuxpolska.com
    name: jmmaro
name: sonarqube
sources:
  - https://github.com/SourceMation/charts.git
type: application
version: 0.4.3
