annotations:
  catalog.cattle.io/display-name: example-chart (1/2) - Operator/Config/App
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
#  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
#  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: example-chart
#  catalog.cattle.io/namespace: example-namespace
apiVersion: v2
appVersion: 1.15.1
dependencies:
- name: common
  repository: https://charts.sourcemation.com/
  version: 0.1.x
- condition: global.exampleCrd.enabled
  name: example-chart
  version: v1.15.1
  repository: https://example-charts/
#- condition: global.appCrd.enabled
#  name: example-chart
#  version: v1.15.1
#  repository: file://../charts/example-chart
- condition: global.exampleChart.enabled
  name: example-chart
  version: v2.16.2
  repository: https://example.charts/
  alias: example-app
description: SHORT-DESCRIPTION. Install only once on kubernetes / Install many times on kubernetes. Security/Monitoring/CICD Classic.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
# dodać nazwy komponentów oraz nazwę kategorii
- example-category
- example chart
- example-chart
#kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
# podaj swoje dane
- email: kamil.kwiatkowski@linuxpolska.com
  name: Qwiatu
name: example-chart
sources:
- https://github.com/SourceMation/charts.git
type: application
version: 0.1.0
