{{- /*
*/}}

{{- if eq $.Values.type "selfSigned" }}
  {{- with $.Values.selfSigned }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- if eq $.Values.scope "cluster" }}
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
  {{- else }}
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
  {{- end }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
  {{- if eq $.Values.scope "cluster" }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
  namespace: {{ .auth.operatorNamespace }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- end }}
spec:
  isCA: true
  commonName: {{ include "common.names.shortname" $ }}
  {{- if eq $.Values.scope "cluster" }}
  secretName: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
  {{- else }}
  secretName: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
  {{- end }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    {{- if eq $.Values.scope "cluster" }}
    name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
    {{- else }}
    name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
    {{- end }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
  {{- if eq $.Values.scope "cluster" }}
kind: ClusterIssuer
metadata:
  name: {{ include "common.names.shortname" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
kind: Issuer
metadata:
  name: {{ include "common.names.shortname" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  namespace: {{ include "common.names.namespace" $ }}
  {{- end }} 
spec:
  ca:
    {{- if eq $.Values.scope "cluster" }}
    secretName: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
    {{- else }}
    secretName: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
    {{- end }}


    {{- if $.Values.global.certManagerApproverPolicyCrd.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
  {{- if eq $.Values.scope "cluster" }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-policy:allow-all
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-policy:allow-all
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
    - "policy.cert-manager.io"
    resources: 
    - "certificaterequestpolicies"
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: 
  {{- if eq $.Values.scope "cluster" }}
    - "{{ include "common.names.shortname" $ }}-{{ $.Values.scope }}"
    - "{{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init"
  {{- else }}
    - "{{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}"
    - "{{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init"
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
  {{- if eq $.Values.scope "cluster" }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-policy:allow-all
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
metadata:
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-policy:allow-all
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if eq $.Values.scope "cluster" }}
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-policy:allow-all
  {{- else }}
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-policy:allow-all
  {{- end }}
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  {{- if eq $.Values.scope "cluster" }}
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- end }}
spec:
  allowed:
    commonName:
      value: '*'
      required: true
    dnsNames:
      values:
      - "*"
    ipAddresses:
      values:
      - '*'
    uris:
      values:
      - '*'
    emailAddresses:
      values:
      - '*'
      required: false
    isCA: true
  constraints:
#      minDuration: 1h
#      maxDuration: 24h
    privateKey:
      algorithm: ECDSA
      minSize: 256
      maxSize: 4096
  selector:
  {{- if eq $.Values.scope "cluster" }}
    issuerRef:
      group: "cert-manager.io"
      name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}-init
      kind: "ClusterIssuer"
  {{- else }}
    issuerRef:
      group: "cert-manager.io"
      name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}-init
      kind: "ClusterIssuer"
  {{- end }}
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  {{- if eq $.Values.scope "cluster" }}
  name: {{ include "common.names.shortname" $ }}-{{ $.Values.scope }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- else }}
  name: {{ include "common.names.shortname" $ }}-{{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  {{- end }}
spec:
  selector:
  {{- if eq $.Values.scope "cluster" }}
    issuerRef:
      group: "cert-manager.io"
      name: "{{ include "common.names.shortname" $ }}"
      kind: "ClusterIssuer"
  {{- else }}
    namespace:
      matchNames:
      - "{{ include "common.names.namespace" $ }}"
  {{- end }}
  {{- $.Values.policy | nindent 2 }}

    {{- end }}


  {{- end }}
{{- end }}
