{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    {{- include "kyvernoplugin.labels" . | nindent 4 }}
  name: {{ include "kyvernoplugin.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - policies
  - policies/status
  - clusterpolicies
  - clusterpolicies/status
  verbs:
  - get
  - list
  - watch
{{- if .Values.blockReports.enabled }}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - policyreports
  - policyreports/status
  - clusterpolicyreports
  - clusterpolicyreports/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
{{- else }}
- apiGroups:
  - '*'
  resources:
  - policyreports
  - clusterpolicyreports
  verbs:
  - get
  - list
{{- end }}
{{- end -}}
