# https://github.com/elastic/elasticsearch/tags
# https://www.elastic.co/guide/en/cloud-on-k8s/2.11/k8s_supported_versions.html
annotations:
  catalog.cattle.io/display-name: Elastic - Agent (3/3)
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
#  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
#  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: elk-agent
#  catalog.cattle.io/namespace: kube-system
#  catalog.cattle.io/auto-install: monitoring-stack-crd=match
apiVersion: v2
appVersion: 8.15.0
dependencies:
- name: common
  repository: https://charts.sourcemation.com/
  version: 0.x.x
description: Install once per k8s. Elastic agent for kubernetes which colecting logs, metrics, traces.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- elasticagent
- elastic agent
- elastic
- elasticsearch
- kibana
- apm
- monitoring
- enterprise search
- fleet
- opentelemetry
#kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: elastic-agent
sources:
- https://github.com/SourceMation/charts.git
type: application
version: 1.4.0
