annotations:
  catalog.cattle.io/display-name: Cert-manager (2/3) - Add-ons
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
#  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
#  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: cert-manager-add-ons
  catalog.cattle.io/namespace: cert-manager
apiVersion: v2
appVersion: 1.2.0
dependencies:
- name: common
  repository: https://charts.sourcemation.com/
  version: 0.1.x

- condition: global.adcsIssuerCrd.enabled
  name: adcs-issuer
  version: 3.0.0
  repository: https://djkormo.github.io/adcs-issuer

- condition: global.trustManagerCrd.enabled
  name: trust-manager
  version: v0.13.0
  repository: https://charts.jetstack.io



description: Add-ons for cert-manager operator. Install once per k8s. Security. 
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- security
- cert manager
- cert-manager
- trust manager
- trust-manger
#kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: cert-manager-add-ons
sources:
- https://github.com/SourceMation/charts.git
type: application
version: 1.2.0
