test:
  securityContext: []
webhooksCleanup:
  securityContext: []
policyReportsCleanup:
  securityContext: []
cleanupJobs:
  admissionReports:
    securityContext: []
  clusterAdmissionReports:
    securityContext: []
admissionController:	
  initContainer:
    securityContext: []
  container:
    securityContext: []
backgroundController:
  securityContext: []
cleanupController:
  securityContext: []
reportsController:
  securityContext: []
