apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}-config
data:
  rabbitmq.conf: |-
    listeners.tcp.default = {{ .Values.rabbitmq.listeners.tcp.default }}
    management.listener.port = {{ .Values.rabbitmq.management.listener.port }}
    management.listener.ssl = {{ .Values.rabbitmq.management.listener.ssl }}
