apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
type: Opaque
data:
  rabbitmq-username: {{ .Values.rabbitmq.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
