{{- /*
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/README.asciidoc
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/stack_monitoring.yaml
*/}}


{{- if $.Values.enterprise_search.enabled  }}

---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ include "common.names.shortname" $ }}-mon-enterprise-search-metricbeat
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  type: metricbeat
  version: {{ default .Chart.AppVersion }}
  image: docker.elastic.co/beats/metricbeat:{{ default .Chart.AppVersion }}
  elasticsearchRef:
    name: {{ include "common.names.shortname" $ }}
  config:
    metricbeat:
      modules:
        - module: enterprisesearch
          metricsets:
            - health
            - stats
          period: 10s
          hosts:
            - https://{{ .Values.enterprise_search.params.ingress.hostname }}
          xpack.enabled: true
          username: {{ .Values.elasticsearch.params.auth.username }}
          password: {{ .Values.elasticsearch.params.auth.password }}
          # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
          # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
          ssl.verification_mode: "none"
          xpack.enabled: true
    processors:
    - add_cloud_metadata: {}
    logging.json: true
  deployment:
    podTemplate:
      metadata:
        labels:
          scrape: beat-{{ include "common.names.namespace" $ }}
      spec:
        # required to read /etc/beat.yml
        securityContext:
          runAsUser: 0
        initContainers:
        - name: wait-for
          image: quay.io/eurolinux/eurolinux-9:latest
          command:
          - /bin/sh
          - -c
          - >
            set -x;
            until curl -f -k -L https://{{ include "common.names.shortname" $ -}}-kb-http:5601; do sleep 2; done

#        - name: wait-for
#          image: busybox:latest
#          command:
#          - /bin/sh
#          - -c
#          - >
#            set -x;
#            until wget -q --spider --no-check-certificate https://{{ include "common.names.shortname" $ -}}-kb-http:5601; do sleep 2; done
        containers:
        - name: metricbeat
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 300Mi

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
#                - key: elastic
#                  operator: In
#                  values:
#                  - all

{{- end }}
