{{- /*
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/README.asciidoc
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/heartbeat_es_kb_health.yaml
*/}}



{{- if or .Values.elasticsearch.enabled .Values.kibana.enabled }}

---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ include "common.names.shortname" $ }}-mon-heartbeat
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  type: heartbeat
  version: {{ default .Chart.AppVersion }}
  image: docker.elastic.co/beats/heartbeat:{{ default .Chart.AppVersion }}
  elasticsearchRef:
    name: {{ include "common.names.shortname" $ }}
  config:
    heartbeat.monitors:
    {{- if .Values.elasticsearch.enabled }}
    - type: http
      id: es-http
      schedule: '@every 5s'
      urls:
      - "{{ include "common.names.shortname" $ }}-es-http.{{ include "common.names.namespace" . }}.svc:9200"
    {{- end }}
    {{- if .Values.kibana.enabled }}
    - type: http
      id: kibana-http
      schedule: '@every 5s'
      urls:
      - "{{ include "common.names.shortname" $ }}-kb-http.{{ include "common.names.namespace" . }}.svc:5601"
    {{- end }}
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
{{- end }}

