annotations:
  catalog.cattle.io/auto-install: kubewarden-crds=1.4.5
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Kubewarden
  catalog.cattle.io/namespace: cattle-kubewarden-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/provides-gvr: policyservers.policies.kubewarden.io/v1
  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <= 2.8.100-0'
  catalog.cattle.io/release-name: rancher-kubewarden-controller
  catalog.cattle.io/requests-cpu: 250m
  catalog.cattle.io/requests-memory: 50Mi
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: kubewarden
  catalog.cattle.io/upstream-version: 2.0.8
apiVersion: v2
appVersion: v1.10.0
dependencies:
- condition: auditScanner.policyReporter
  name: policy-reporter
  repository: https://kyverno.github.io/policy-reporter
  version: 2.21.6
description: A Helm chart for deploying the Kubewarden stack
home: https://www.kubewarden.io/
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
keywords:
- Kubewarden
- Security
- Infrastructure
- Monitoring
- policy agent
- policies
- validating webhook
- admissions controller
- policy report
- audit scanner
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: kubewarden@suse.de
  name: Kubewarden Maintainers
  url: https://github.com/orgs/kubewarden/teams/maintainers
name: kubewarden-controller
type: application
version: 2.0.8
