global:
  adcsIssuer:
    enabled: true

adcs-issuer:
  controllerManager:
    rbac:
      enabled: true
      serviceAccountName: adcs-issuer      
      certManagerNamespace: cert-manager   
      certManagerServiceAccountName: cert-manager 
    replicas: 2
    arguments:
      cluster-resource-namespace: cert-manager
#    environment:
#      KUBERNETES_CLUSTER_DOMAIN: cluster.local
#      ENABLE_WEBHOOKS: "false"                 
#      ENABLE_DEBUG: "true"                    
  
  simulator:
    enabled: false
    exampleCertificate:
      enabled: false

  affinity:
    nodeAffinity: {}                          # Node affinity rules for the simulator pods.
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: kubernetes.io/e2e-az-name
    #         operator: In
    #         values:
    #         - e2e-az1
    #         - e2e-az2
    podAffinity: {}                           # Pod affinity rules for the simulator pods.
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: security
      #       operator: In
      #       values:
      #       - S1
      #   topologyKey: "kubernetes.io/hostname"
    podAntiAffinity: {}                       # Pod anti-affinity rules for the simulator pods.
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   - labelSelector:
      #       matchExpressions:
      #       - key: app
      #         operator: In
      #         values:
      #         - "my-app"
      #     topologyKey: "kubernetes.io/hostname"
