############ redisStandalone ############
# redisStandalone:
#   image: quay.io/opstree/redis
#   tag: v7.0.15
#   imagePullPolicy: IfNotPresent
#   imagePullSecrets: []
#   redisSecret:
#     secretName: ""
#     secretKey: ""
#   serviceType: ClusterIP
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "250m"
#     limits:
#       memory: "512Mi"
#       cpu: "500m"
#   ignoreAnnotations: []
#   minReadySeconds: 0
#   recreateStatefulSetOnUpdateInvalid: false

############ redisCluster ############
# redisCluster:
#   clusterSize: 3
#   clusterVersion: v7
#   persistenceEnabled: true
#   image: quay.io/opstree/redis
#   tag: v7.0.15
#   imagePullPolicy: IfNotPresent
#   imagePullSecrets: {}
#   redisSecret:
#     secretName: ""
#     secretKey: ""
#   resources: {}
#   minReadySeconds: 0
#   recreateStatefulSetOnUpdateInvalid: false
#   leader:
#     replicas: 3
#     serviceType: ClusterIP
#     affinity: {}
#     tolerations: []
#     nodeSelector: null
#     securityContext: {}
#     pdb:
#       enabled: false
#       maxUnavailable: 1
#       minAvailable: 1
    
#   follower:
#     replicas: 3
#     serviceType: ClusterIP
#     affinity: null
#     tolerations: []
#     nodeSelector: null
#     securityContext: {}
#     pdb:
#       enabled: false
#       maxUnavailable: 1
#       minAvailable: 1

############ redisReplication ############
# redisReplication:
#   clusterSize: 3
#   image: quay.io/opstree/redis
#   tag: v7.0.15
#   imagePullPolicy: IfNotPresent
#   imagePullSecrets: []
#   redisSecret:
#     secretName: ""
#     secretKey: ""
#   serviceType: ClusterIP
#   resources: {}
#   ignoreAnnotations: []
#   minReadySeconds: 0
#   recreateStatefulSetOnUpdateInvalid: false

############ redisSentinel ############
# redisSentinel:
#   clusterSize: 3
#   image: quay.io/opstree/redis-sentinel
#   tag: v7.0.15
#   imagePullPolicy: IfNotPresent
#   imagePullSecrets: []
#   redisSecret:
#     secretName: ""
#     secretKey: ""
#   serviceType: ClusterIP
#   resources: {}
#   ignoreAnnotations: []
#   minReadySeconds: 0
#   recreateStatefulSetOnUpdateInvalid: false

# redisSentinelConfig:
#   redisReplicationName: "redis-replication"
#   redisReplicationPassword:
#     secretName: ""
#     secretKey: ""
#   masterGroupName: ""
#   resolveHostnames: ""
#   announceHostnames: ""
#   redisPort: ""
#   quorum: ""
#   parallelSyncs: ""
#   failoverTimeout: ""
#   downAfterMilliseconds: ""

# pdb:
#   enabled: false
#   minAvailable: 1
#   maxUnavailable: null

# livenessProbe:
#   failureThreshold: 3
#   initialDelaySeconds: 1
#   periodSeconds: 10
#   successThreshold: 1
#   timeoutSeconds: 1

# readinessProbe:
#   failureThreshold: 3
#   initialDelaySeconds: 1
#   periodSeconds: 10
#   successThreshold: 1
#   timeoutSeconds: 1

############ ALL ############
# externalConfig:
#   enabled: false
#   data: |
#     tcp-keepalive 400
#     slowlog-max-len 158
#     stream-node-max-bytes 2048

### standalone
# externalService:
#   enabled: true
#   serviceType: ClusterIP
#   port: 6379
### cluster
# externalService:
#   enabled: false
#   serviceType: LoadBalancer
#   port: 6379
### replica
# externalService:
#   enabled: false
#   serviceType: NodePort
#   port: 6379
### sentinel
# externalService:
#   enabled: false
#   serviceType: NodePort
#   port: 26379

# serviceMonitor:
#   enabled: false
#   interval: 30s
#   scrapeTimeout: 10s
#   namespace: monitoring
#   extraLabels: {}

# redisExporter:
#   enabled: false
#   image: quay.io/opstree/redis-exporter
#   tag: "v1.44.0"
#   imagePullPolicy: IfNotPresent
#   resources: {}
#   env: []
#   securityContext: {}

# sidecars:
#   name: ""
#   image: ""
#   imagePullPolicy: "IfNotPresent"
#   resources:
#     limits:
#       cpu: "100m"
#       memory: "128Mi"
#     requests:
#       cpu: "50m"
#       memory: "64Mi"
#   env: {}

# initContainer:
#   enabled: false
#   image: ""
#   imagePullPolicy: "IfNotPresent"
#   resources: {}
#   env: []
#   command: []
#   args: []

# priorityClassName: ""

# nodeSelector: {}

### standalone & replica
# storageSpec:
#   volumeClaimTemplate:
#     spec:
#       storageClassName: standard
#       accessModes: ["ReadWriteOnce"]
#       resources:
#         requests:
#           storage: 1Gi
#       selector: {}
### cluster
# storageSpec:
#   volumeClaimTemplate:
#     spec:
#       accessModes: ["ReadWriteOnce"]
#       resources:
#         requests:
#           storage: 1Gi
#   nodeConfVolume: true
#   nodeConfVolumeClaimTemplate:
#     spec:
#       accessModes: ["ReadWriteOnce"]
#       resources:
#         requests:
#           storage: 1Gi

# podSecurityContext:
#   runAsUser: 1000
#   fsGroup: 1000

# TLS:
#   ca: ca.key
#   cert: tls.crt
#   key: tls.key
#   secret:
#     secretName: ""

# acl:
#   secret:
#     secretName: ""

# env: []
# securityContext: {}
# affinity: {}
# tolerations: []
# serviceAccountName: ""
# labels: {}