redisStandalone:
#  name: ""
#  image: quay.io/opstree/redis
#  tag: v7.0.15
#  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
    # - name:  Secret with Registry credentials
#  redisSecret:
#    secretName: ""
#    secretKey: ""
#  serviceType: ClusterIP
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "250m"
#    limits:
#      memory: "512Mi"
#      cpu: "500m"
#  ignoreAnnotations: []
#  minReadySeconds: 0
#  recreateStatefulSetOnUpdateInvalid: false

# labels: {}
#   foo: bar
#   test: echo

# externalConfig:
#   enabled: false
#   data: |
#     tcp-keepalive 400
#     slowlog-max-len 158
#     stream-node-max-bytes 2048

# externalService:
#   enabled: true
#   serviceType: ClusterIP
#   port: 6379

# serviceMonitor:
#   enabled: false
#   interval: 30s
#   scrapeTimeout: 10s
#   namespace: monitoring
#   extraLabels: {}

# redisExporter:
#   enabled: false
#   image: quay.io/opstree/redis-exporter
#   tag: "v1.44.0"
#   imagePullPolicy: IfNotPresent
#   resources: {}
#   env: []
#   securityContext: {}

# initContainer:
#   enabled: false
#   image: ""
#   imagePullPolicy: "IfNotPresent"
#   resources: {}
#   env: []
#   command: []
#   args: []

# sidecars:
#   name: ""
#   image: ""
#   imagePullPolicy: "IfNotPresent"
#   resources:
#     limits:
#       cpu: "100m"
#       memory: "128Mi"
#     requests:
#       cpu: "50m"
#       memory: "64Mi"
#   env: []

# priorityClassName: ""

nodeSelector: {}

# storageSpec:
#   volumeClaimTemplate:
#     spec:
#       storageClassName: standard
#       accessModes: ["ReadWriteOnce"]
#       resources:
#         requests:
#           storage: 1Gi
#       selector: {}

# podSecurityContext:
#   runAsUser: 1000
#   fsGroup: 1000

# securityContext: {}

affinity: {}
# tolerations: []
# serviceAccountName: ""

# TLS:
#   ca: ca.key
#   cert: tls.crt
#   key: tls.key
#   secret:
#     secretName: ""

# acl:
#   secret:
#     secretName: ""

# env: []
