global:
  certManagerApproverPolicyCrd:
    enabled: true

# possible values: cluster,namespace
scope: "cluster"

# possible values: selfSigned,adcs
type: 'selfSigned'

selfSigned:
  auth:
    operatorNamespace: cert-manager

adcs:
  url: 'http://cawe.example.com/certsrv'
  templateName: ''
  auth:
    operatorNamespace: cert-manager
    username: ''
    password: ''
    # paste CAWE's CA
    caBundle: |-

policy: |-
  allowed:
    commonName:
      value: '*'
      required: false
    dnsNames:
      values:
      - "*"
    ipAddresses:
      values:
      - '*'
    uris:
      values:
      - '*'
    emailAddresses:
      values:
      - '*'
      required: false
    isCA: false
    usages:
    - server auth
    - client auth
    - signing
    - digital signature
    - content commitment
    - key encipherment
    - key agreement
    - cert sign
    - encipher only
    - decipher only
    - any
    - code signing
    - email protection
    - s/mime
    - ipsec end system
    - ipsec tunnel
    - ipsec user
    - timestamping
    - ocsp signing
    - microsoft sgc
    - netscape sgc
    subject:
      organizations:
        values: 
        - '*'
      countries:
        values: 
        - '*'
      organizationalUnits:
        values: 
        - '*'
      localities:
        values: 
        - '*'
      provinces:
        values: 
        - '*'
      streetAddresses:
        values: 
        - '*'
      postalCodes:
        values: 
        - '*'
      serialNumber:
        value: '*'
  constraints:
    privateKey:
      algorithm: RSA
      minSize: 2048
      maxSize: 4096



questionsSpec:
  policy: |-
    allowed:
      commonName:
        value: '*'
        required: false
      dnsNames:
        values:
        - "*"
      ipAddresses:
        values:
        - '*'
      uris:
        values:
        - '*'
      emailAddresses:
        values:
        - '*'
        required: false
      isCA: true
      usages:
      - server auth
      - client auth
      - signing
      - digital signature
      - content commitment
      - key encipherment
      - key agreement
      - cert sign
      - encipher only
      - decipher only
      - any
      - code signing
      - email protection
      - s/mime
      - ipsec end system
      - ipsec tunnel
      - ipsec user
      - timestamping
      - ocsp signing
      - microsoft sgc
      - netscape sgc
      subject:
        organizations:
          values: 
          - '*'
        countries:
          values: 
          - '*'
        organizationalUnits:
          values: 
          - '*'
        localities:
          values: 
          - '*'
        provinces:
          values: 
          - '*'
        streetAddresses:
          values: 
          - '*'
        postalCodes:
          values: 
          - '*'
        serialNumber:
          value: '*'
    constraints:
      minDuration: 1h
      maxDuration: 24h
      privateKey:
        algorithm: RSA
        minSize: 2048
        maxSize: 4096

nameOverride: ''
namespaceOverride: ''
