---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name:  {{ include "elastic.fullname" . }}
  namespace: {{ include "elastic.namespace" . }}
  labels:
    scrape: ls
spec:
  count: 1
  version: {{ .Values.image.tag | default .Chart.AppVersion }}
  image: docker.elastic.co/logstash/logstash:{{ .Values.image.tag | default .Chart.AppVersion }}
  elasticsearchRefs:
  - clusterName:  eck
    name: {{ include "elastic.fullname" . }}
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: {{ include "elastic.fullname" . }}
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            user => "${ECK_ES_USER}"
            password => "${ECK_ES_PASSWORD}"
            ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  services:
  - name: beats
    service:
      spec:
        type: LoadBalancer
        selector:
          common.k8s.elastic.co/type: logstash
          logstash.k8s.elastic.co/name: {{ include "elastic.fullname" . }}
        ports:
          - port: 5044
            name: "filebeat"
            protocol: TCP
            targetPort: 5044
  podTemplate:
    spec:
      containers:
      - name: logstash
        env:
        - name: LS_JAVA_OPTS   
          value: "-Xmx2g -Xms2g"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
#              - key: elastic
#                operator: In
#                values:
#                - all

