{{- if .Values.jenkins.controller.ingress.enabled }}
{{- $tls := first .Values.jenkins.controller.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.names.shortname" $ }}-tls-cert
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  secretName: "{{ $tls.secretName }}"
  isCA: false
  usages:
    - server auth
    - client auth
    - key encipherment
    - digital signature
  commonName: "{{ .Values.jenkins.controller.ingress.hostName }}"
  dnsNames:
    - "{{ .Values.jenkins.controller.ingress.hostName }}"
  issuerRef:
    group: cert-manager.io
    name: "{{ .Values.jenkins.controller.ingress.cert.issuerName }}"
    kind: "{{ .Values.jenkins.controller.ingress.cert.issuerKind }}"
{{- end }}
