---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: {{ $.Values.clusterImageCatalog.name }}
spec:
  images:
  {{- with $.Values.clusterImageCatalog.images }}
    {{- toYaml . | nindent 4 }}
  {{- end }}