{{- range $k, $v := $.Values.clusterImageCatalog }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: {{ $v.name }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
spec:
  images:
  {{- with $v.images }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}